using System;

//#pragma warning disable 1591

namespace PdfSharp
{
  /// <summary>
  /// Represents IDs for error and diagnostic messages generated by PDFsharp.
  /// </summary>
  public enum PSXMsgID
  {
    //// ----- General Messages ---------------------------------------------------------------------

    //SampleMessage1,
    //SampleMessage2,

    //// ----- XGraphics Messages -------------------------------------------------------------------

    //// ----- PDF Messages -------------------------------------------------------------------------

    //NameMustStartWithSlash,
    //UserOrOwnerPasswordRequired,

    //// ----- PdfParser Messages -------------------------------------------------------------------

    //UnexpectedToken,
    //UnknownEncryption,

  }
}